source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2’
use_frameworks!

target 'PM2.5’ do
    pod 'Alamofire', '~> 4.3'
    pod 'Kingfisher', '~> 3.3.1’
    pod 'SwiftyJSON', '~> 3.1.4’
    pod 'PKHUD' , '~> 4.2.0’
    pod 'MJRefresh'

end