source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘8.0’
use_frameworks!

target 'PM2.5’ do
    pod 'Alamofire', '~> 4.3'
    pod 'SwiftyJSON', '~> 3.1.4’
    pod 'PKHUD’, :git => 'https://github.com/pkluz/PKHUD.git'

    pod 'MJRefresh'
    pod 'Onboard'
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
    pod 'Reachability'
    pod 'IGListKit', '~> 2.0.0'
    pod 'Charts', '~> 3.0.2'

# 主模块(必须)
pod 'ShareSDK3', '~> 3.3.2'

# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
pod 'MOBFoundation', '~> 2.0.8'


# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'

# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'

end
